### ISSUE TITLE
the result of ifnull(xx,count(distinct xx)) is not as expected

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#3595]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t(a int,b date);
insert into t values(1,"2020-10-10");
alter table t set tiflash replica 1;
set @@tidb_enforce_mpp=on;
select ifnull(max(b) = max('08:45:16'), count(a)) from t; -- 1
select ifnull(max(b) = max('08:45:16'), count(distinct a)) from t; -- 0 ,bug expect 1
/*
+--------------------------------------+---------+-------------------+---------------+----------------------------------------------------------------------------------------------------------+
| id                                   | estRows | task              | access object | operator info                                                                                            |
+--------------------------------------+---------+-------------------+---------------+----------------------------------------------------------------------------------------------------------+
| TableReader_28                       | 1.00    | root              |               | data:ExchangeSender_27                                                                                   |
| └─ExchangeSender_27                  | 1.00    | batchCop[tiflash] |               | ExchangeType: PassThrough                                                                                |
|   └─Projection_5                     | 1.00    | batchCop[tiflash] |               | ifnull(eq(Column#4, cast(Column#5, datetime(6) BINARY)), Column#6)->Column#7                             |
|     └─Projection_23                  | 1.00    | batchCop[tiflash] |               | Column#4, Column#5, Column#6                                                                             |
|       └─HashAgg_24                   | 1.00    | batchCop[tiflash] |               | funcs:max(Column#13)->Column#4, funcs:max(Column#14)->Column#5, funcs:count(distinct test.t.a)->Column#6 |
|         └─ExchangeReceiver_26        | 1.00    | batchCop[tiflash] |               |                                                                                                          |
|           └─ExchangeSender_25        | 1.00    | batchCop[tiflash] |               | ExchangeType: PassThrough                                                                                |
|             └─HashAgg_22             | 1.00    | batchCop[tiflash] |               | group by:test.t.a, funcs:max(test.t.b)->Column#13, funcs:max("08:45:16")->Column#14                      |
|               └─TableFullScan_15     | 1.00    | batchCop[tiflash] | table:t       | keep order:false, stats:pseudo                                                                           |
+--------------------------------------+---------+-------------------+---------------+----------------------------------------------------------------------------------------------------------+
```
### 2. What did you expect to see? (Required)
1
### 3. What did you see instead (Required)
0
### 4. What is your TiFlash version? (Required)
master
65f9c36e0f5ea9fb03cb5d99651b86299bfac699

**Comment by yibin87** [comment]
Different results of count(a)/count(distinct a) due to different plans:
mysql> explain select ifnull(max(b) = max('08:45:16'), count(a)) from t;
+----------------------------+---------+-----------+---------------+-------------------------------------------------------------------------------------------------+
| id                         | estRows | task      | access object | operator info                                                                                   |
+----------------------------+---------+-----------+---------------+-------------------------------------------------------------------------------------------------+
| Projection_4               | 1.00    | root      |               | ifnull(eq(Column#4, cast(Column#5, datetime(6) BINARY)), Column#6)->Column#7                    |
| └─StreamAgg_11             | 1.00    | root      |               | funcs:max(test.t.b)->Column#4, funcs:max("08:45:16")->Column#5, funcs:count(test.t.a)->Column#6 |
|   └─TableReader_17         | 1.00    | root      |               | data:TableFullScan_16                                                                           |
|     └─TableFullScan_16     | 1.00    | cop[tikv] | table:t       | keep order:false, stats:pseudo                                                                  |
+----------------------------+---------+-----------+---------------+-------------------------------------------------------------------------------------------------+
4 rows in set (0.00 sec)

**Comment by yibin87** [comment]
Different results of count(a)/count(distinct a) due to different plans:
mysql> explain select ifnull(max(b) = max('08:45:16'), count(a)) from t;
+----------------------------+---------+-----------+---------------+-------------------------------------------------------------------------------------------------+
| id                         | estRows | task      | access object | operator info                                                                                   |
+----------------------------+---------+-----------+---------------+-------------------------------------------------------------------------------------------------+
| Projection_4               | 1.00    | root      |               | ifnull(eq(Column#4, cast(Column#5, datetime(6) BINARY)), Column#6)->Column#7                    |
| └─StreamAgg_11             | 1.00    | root      |               | funcs:max(test.t.b)->Column#4, funcs:max("08:45:16")->Column#5, funcs:count(test.t.a)->Column#6 |
|   └─TableReader_17         | 1.00    | root      |               | data:TableFullScan_16                                                                           |
|     └─TableFullScan_16     | 1.00    | cop[tikv] | table:t       | keep order:false, stats:pseudo                                                                  |
+----------------------------+---------+-----------+---------------+-------------------------------------------------------------------------------------------------+
4 rows in set (0.00 sec)

**Comment by yibin87** [comment]
It looks strange that max(b) and count(a) is not pushed down to tiflash.

**Comment by yibin87** [comment]
Currently，some function's paremter applied "cast xx as datetime", and its behavior will be affected:
select monthname('0001-01-00'); will result to January
However, if push down to tiflash, the expression will be like:
select monthname(cast('0001-01-00' as datetime)); which will be null.
