### ISSUE TITLE
`BlockInputStream->dumpTree()` is very slow if the input stream tree contains multiple `SharedQueryBlockInputStream`

### ISSUE THREAD

**Issue by windtalker** [pingcap/tiflash#4494]
## Bug Report

Please answer these questions before submitting your issue. Thanks!
For a query pipeline:
```
Union
 ExchangeSender × 36
  Expression
   SharedQuery
    ParallelAggregating
     Expression × 36
      Expression
       Expression
        Expression
         Expression
          Expression
           Expression
            Expression
             Expression
              Expression
               Expression
                Expression
                 Expression
                  Expression
                   SharedQuery
                    ParallelAggregating
                     Expression × 36
                      Expression
                       Expression
                        Expression
                         Squashing
                          TiRemoteBlockInputStream(ExchangeReceiver)
```
It took more than 3 second with intel i710700F for function call [DumpTree](https://github.com/pingcap/tiflash/blob/aa6263348a51d8fa10409c3d342e5ff315f22d65/dbms/src/DataStreams/IBlockInputStream.cpp#L77).

**Comment by JaySon-Huang** [comment]
Mark that this problem is more noticeable on the arm64 platform. This is because the efficiency of the `IBlockInputStream::dumpTree` function is O(n^2) where n is the number of CPU cores and arm64 platforms generally have more CPU cores than x86 platforms.

The performance of TPC-DS query 75 is greatly affected by this problem.
