### ISSUE TITLE
compiler error [[maybe_unused]]

### ISSUE THREAD

**Issue by fzhedu** [pingcap/tiflash#4615]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
compile tiflash on centos using gcc v7.3.1

```
/data2/fzh/tiflash/dbms/src/Common/CPUAffinityManager.h:118:26: error: ‘maybe_unused’ attribute ignored [-Werror=attributes]
     [[maybe_unused]] int query_cpu_percent;
                          ^~~~~~~~~~~~~~~~~
/data2/fzh/tiflash/dbms/src/Common/CPUAffinityManager.h:119:26: error: ‘maybe_unused’ attribute ignored [-Werror=attributes]
     [[maybe_unused]] int cpu_cores;
```

### 4. What is your TiFlash version? (Required)
master

**Comment by ywqzzy** [comment]
In my env(ubuntu 20.04, gcc v7.x),  the same error occured. I just remove the [[maybe_unused]] attribute. I am not sure if it is legal to do this.

**Comment by JaySon-Huang** [comment]
If we don't add `[[maybe_unused]]` attribute for those variables, when we compile TiFlash under MacOS using clang, we will get compile error since those variables are unused private members.
However, GCC don't check for unused private members, so adding `[[maybe_unused]]` for variables will be ignore. you can checkout the details in this StackOverflow question: https://stackoverflow.com/questions/50646334/maybe-unused-on-member-variable-gcc-warns-incorrectly-that-attribute-is

Maybe the best way to handle it is wrap those lines by 
```
#ifdef __clang__
#pragma GCC diagnostic ignored "-Wno-unused-private-field"
#endif

  // those variables

#ifdef __clang__
#pragma GCC diagnostic pop
#endif
```

**Comment by JaySon-Huang** [comment]
Fixed by https://github.com/pingcap/tiflash/pull/4700
