### ISSUE TITLE
Needs doc about running static analysis checks locally

### ISSUE THREAD

**Issue by breezewish** [pingcap/tiflash#4892]
## Enhancement

Currently clang-tidy in the CI is not using a config specified by TiFlash, but rather a default one:

https://ci.pingcap.net/blue/organizations/jenkins/tiflash-build-common/detail/tiflash-build-common/4772/pipeline/208

Additionally, we should give instructions about how to run clang-tidy locally for the community. It is a waste of CI resources if it can be only run in the CI.

**Comment by JaySon-Huang** [comment]
here is a script for how to run clang-tidy in local https://github.com/pingcap/tiflash/issues/4605

**Comment by Lloyd-Pottiger** [comment]
maybe due to the execution path of `python3 /home/jenkins/agent/workspace/tiflash-build-common/tiflash/release-centos7-llvm/scripts/run-clang-tidy.py -p /home/jenkins/agent/workspace/tiflash-build-common/build -j 40 --files '.*/tiflash/dbms/*'` is not under `/home/jenkins/agent/workspace/tiflash-build-common/tiflash` ?

**Comment by breezewish** [comment]
After some experiment I believe this is a misleading output. The clang-tidy will in fact use the tidy file specified in the project root at the file level.

However we will still need some instructions about how to run it locally.
