### ISSUE TITLE
Use a file-system abstraction to simplify compute-storage decouple

### ISSUE THREAD

**Issue by fuzhe1989** [pingcap/tiflash#5036]
## Enhancement

https://fuzhe1989.github.io/2022/05/29/build-cloud-native-kv-engine-based-on-a-dfs/

**Comment by flowbehappy** [comment]
Great idea! Your blog is very inspiring. While I'm working on a plan to migrate TiFlash to true cloud native architecture. Will share it with you soon. Some key points of the design:

1. TiFlash needs to handle realtime, high frequent ingestion, so all io besides WAL directly going to S3 is not very practical.    So we will need a place to hold the "delta" data.
2. Since caching is critical to query performance, like Snowflake, we would like to do caching directly on the local SSD.
3. Compute nodes need to find an intelligent way to fetch the latest delta data from the storage nodes.
