### ISSUE TITLE
TiFlash crash when Aggregation FailPoints in createAggregateStates triggers

### ISSUE THREAD

**Issue by yibin87** [pingcap/tiflash#5356]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Turns on [Aggregation RandomFail point](https://github.com/yibin87/tiflash/blob/4e86896372885764cd62a0e8dafa8d6c7017ca14/dbms/src/Interpreters/Aggregator.cpp#L342)
2. Prepare TPCH database, SF=10,  run query_13.sql parrelly, you'll get core dump, and stack trace like this:
![image](https://user-images.githubusercontent.com/12403562/178426189-aa5a04ee-df19-4f11-9e00-6380fbafba59.png)

### 2. What did you expect to see? (Required)
TiFlash no crash.
### 4. What is your TiFlash version? (Required)
v6.2.0-alpha-nightly-20220710

**Comment by gengliqi** [comment]
I try this failpoint by using master code and find there is no crash.

The bug is very likely caused by the aggregation of non-joined data after an exception happened.

In my previous attempt, I change the code line of 201 to `parent.cancel(false);`. https://github.com/pingcap/tiflash/blob/764bd3c9801d37b9b9157944d054846005e4080a/dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp#L192-L202 
Then the crash doesn't happen anymore because the aggregation code of non-joined data isn't triggered. (see the code below)
https://github.com/pingcap/tiflash/blob/764bd3c9801d37b9b9157944d054846005e4080a/dbms/src/Interpreters/Aggregator.cpp#L519-L529

However, this line of code doesn't change at present. 
Why does the crash not happen? It's due to https://github.com/pingcap/tiflash/pull/5274.
In this PR, if an exception happens, the non-join data will not be fetched anymore so the aggregation code of them will not be triggered as well.

By the way, I think the code line of 201 still needs to be changed though it seems no harm for now.
https://github.com/pingcap/tiflash/blob/764bd3c9801d37b9b9157944d054846005e4080a/dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp#L192-L202

**Comment by gengliqi** [comment]
Maybe we can close this issue or change the severity to minor?

**Comment by gengliqi** [comment]
The bug is introduced by https://github.com/pingcap/tiflash/pull/3434.
