### ISSUE TITLE
TiFlash can't gc completely for CHbenCHmark scenario

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#6039]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> select TIFLASH_INSTANCE,tidb_table, total_size,total_stable_size_on_disk from information_schema.tiflash_tables where tidb_database='tpcc' and total_size !=0 or total_stable_size_on_disk !=0 order by tidb_table;
+---------------------------------------------------------------------------------------+------------+------------+---------------------------+
| TIFLASH_INSTANCE                                                                      | tidb_table | total_size | total_stable_size_on_disk |
+---------------------------------------------------------------------------------------+------------+------------+---------------------------+
| tc-tiflash-0.tc-tiflash-peer.endless-htap-ch-mutiple-disks-tps-1290764-1-284.svc:3930 | new_order  |   16645768 |                   9491563 |
| tc-tiflash-3.tc-tiflash-peer.endless-htap-ch-mutiple-disks-tps-1290764-1-284.svc:3930 | order_line |   97287435 |                  39894332 |
+---------------------------------------------------------------------------------------+------------+------------+---------------------------+
```
![253692a1-ecd6-4e71-960f-5c4fe8d5b276](https://user-images.githubusercontent.com/7677963/192421223-99f0aed2-163a-4924-a349-5fdbfbcb82e9.jpeg)

### 4. What is your TiFlash version? (Required)
6.3 ca8f97df64b12b326ae2282b992785da1f7ebac0

**Comment by breezewish** [comment]
We use delete range to clear the data in the old range, when region range is changed during ApplySnapshot:

```cpp
                    auto old_key_range = DM::RowKeyRange::fromRegionRange(
                        old_region->getRange(),
                        table_id,
                        storage->isCommonHandle(),
                        storage->getRowKeyColumnSize());
                    if (old_key_range != new_key_range)
                    {
                        LOG_FMT_INFO(log, "clear region {} old range {} before apply snapshot of new range {}", region_id, old_key_range.toDebugString(), new_key_range.toDebugString());
                        dm_storage->deleteRange(old_key_range, context.getSettingsRef());
                    }
```

(introduced in https://github.com/pingcap/tiflash/issues/4414 as a bug fix).

However, the delete range is not flushed, so that it will not be counted in the GC process (due to https://github.com/pingcap/tiflash/issues/6045), leaving some data not reclaimed.

Previously this case is very rare, because we always flush the segment in the ingestSnapshot process and the segment is usually the same one even when region range is changed.

However, now we use logical split when ingesting snapshots (introduced in https://github.com/pingcap/tiflash/issues/5237), so that the segment for the old region range is very likely to be different than the segment for the new region range. This case becomes more easily to cause problems now.
