### ISSUE TITLE
Group by multi string column in cop/batchCop mode will truncate the last char of group by columns

### ISSUE THREAD

**Issue by windtalker** [pingcap/tiflash#6294]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
create a TiDB cluster with v6.3.0
```
mysql> create table test(a varchar(12) not null, b varchar(17) not null);  
Query OK, 0 rows affected (0.07 sec)

mysql> alter table test set tiflash replica 1;
Query OK, 0 rows affected (0.07 sec)

mysql> insert into test values('203','003004'),('606','003004');
Query OK, 2 rows affected (0.01 sec)
Records: 2  Duplicates: 0  Warnings: 0
mysql> set tidb_allow_mpp=0;
Query OK, 0 rows affected (0.00 sec)
mysql>  select /*+ agg_to_cop() */ a, b from test where b='003004' group by a, b;
+---------+---------+
| a | b |
+---------+---------+
| 20      | 00300   |
| 60      | 00300   |
+---------+---------+
2 rows in set (0.00 sec)

```

### 2. What did you expect to see? (Required)
the query result should be 
```
+---------+---------+
| a | b |
+---------+---------+
| 203     | 003004  |
| 606     | 003004  |
+---------+---------+

```
### 3. What did you see instead (Required)
the query result is 
```
+---------+---------+
| a | b |
+---------+---------+
| 20      | 00300   |
| 60      | 00300   |
+---------+---------+

```
### 4. What is your TiFlash version? (Required)
v6.3.0
### 5. Root cause
This bug is caused by #5834. In #5834, it introduced a new hash method named `HashMethodMultiString`, in `HashMethodMultiString`, for string without collator, it uses 
```
StringRef key(chars[key_index] + last_offset, offsets[key_index][row] - last_offset - 1);
```
as the key, it is not right, because `ColumnString::deserializeAndInsertFromArena` actually assumes that the key is including the terminating zero.
This bug seems can't reproduced in master branch, but we still need to double confirm it.

**Comment by solotzg** [comment]
Root cause
- HashMethodMultiString is used when all agg keys are type string. 
https://github.com/pingcap/tiflash/blob/dfda5682031f607047209da8b1e42fee96bacb91/dbms/src/Common/ColumnsHashing.h#L135-L225 
If collation is not used, the expected way to serialized string column should keep tail zero byte.
https://github.com/pingcap/tiflash/blob/dfda5682031f607047209da8b1e42fee96bacb91/dbms/src/Common/ColumnsHashing.h#L207-L212

----

This bug only affect release-6.3. `HashMethodMultiString` is no longer used since https://github.com/pingcap/tiflash/pull/6135

**Comment by windtalker** [comment]
close this issue since the bug only exists in v6.3.0 and there is no patch version for v6.3.x
