### ISSUE TITLE
Switch default AsyncRequestHandler to v1

### ISSUE THREAD

**Issue by xzhangxian1008** [pingcap/tiflash#7507]
## Enhancement

Daily random fail point fails with AsyncRequestHandlerV2. Other pr may bring in the bug and we need to close the AsyncRequestHandlerV2 to exclude this circumstance.

**Comment by Lloyd-Pottiger** [comment]
Could you please list some problems?

**Comment by xzhangxian1008** [comment]
> Could you please list some problems?

The title may be misleading, more prs will be pushed for refine the AsyncRequestHandlerv2 and I just need a issue for prs to link to.

**Comment by Lloyd-Pottiger** [comment]
> > Could you please list some problems?
> 
> The title may be misleading, more prs will be pushed for refine the AsyncRequestHandlerv2 and I just need a issue for prs to link to.

I think you should describe the problems, what you want to do, and why does your fix can help in prs or issues. Rather than open an issue without any words, and the pr also lack of description.

When other contributors read your codes, we may get confused. If the pr or issue clearly described, it can helps a lot.

**Comment by xzhangxian1008** [comment]
> 

okk, I will describe the context more specifically and change the title.
