### ISSUE TITLE
TiFlash read snapshot can't be released for long time in the cancel mpp scenario

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#7587]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Approximately 10 concurrent executions of the "SELECT COUNT(*) FROM t" statement were used to access tiflash. When the query reported an error, the next round of queries immediately commenced. When injecting tiflash restart chaos to the cluster, the mpp query count increased suddenly, and the tiflash snapshot was not released for a long time.
![image](https://github.com/pingcap/tiflash/assets/7677963/fa62177d-cec8-45c1-997b-2c48c8a39343)
![image](https://github.com/pingcap/tiflash/assets/7677963/311744f0-d98d-4d47-bb72-cd53edbbefbc)
![image](https://github.com/pingcap/tiflash/assets/7677963/973a7ec0-6236-473a-ab3f-f0b57aa079a4)

### 4. What is your TiFlash version? (Required)
master

**Comment by windtalker** [comment]
Two things can be improved
1. In TiDB side, if there is any region does not have an alive TiFlash, TiDB will just send the tasks to all the existing TiFlash, this will almost certainly cause the query fail because it will send task to TiFlash nodes that is not alive. I think it can be improved by 
- Just throw error if some regions don't have an alive replica
- Or still construct mpp tasks based only on the alive TiFlash nodes
2. In TiFlash, `FlashService::CancelMPPTask` is an async method, when TiDB meet error, it will call `FlashService::CancelMPPTask` to cancel current query, but since `FlashService::CancelMPPTask` is an async method, return from TiFlash does not means the cancel is done. And for this issue, the test's code will keep retry immediately when the query meet error. This immediate retry makes TiFlash's handing mpp task number increased so rapidly, and the concurrent query count is out of control. An improvement is to `FlashService::CancelMPPTask` wait a little time before it return to TiDB.

**Comment by SeaRise** [comment]
Maybe having tidb mppgather and mpptask heartbeat would solve the problem?
If mpptask fails to ping tidb mppgather for a long time, it will be released automatically.

**Comment by zanmato1984** [comment]
Should be fixed by https://github.com/pingcap/tiflash/pull/7589.

Please reopen if it occurs again.
