### ISSUE TITLE
only gbk charset failed in this way

### ISSUE THREAD

**Issue by shawn0915** [pingcap/tiflash#7880]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

mini reproduce step pls refer to https://asktug.com/t/topic/1010010

### 2. What did you expect to see? (Required)
should not get error when `alter table tgbk     set tiflash replica 1;`
or, should be get error when use other charset except utf8
or, tiflash already support gbk

![2023-08-02_104845](https://github.com/pingcap/tiflash/assets/17957066/6f6e3823-bc1f-4d0e-9fca-585fdb1a73f8)

### 4. What is your TiFlash version? (Required)
7.2

**Comment by windtalker** [comment]
TiFlash does not support gbk yet, and the expected behavior is: TiDB should throw error when user trying to add TiFlash
 replica for a table that contains gbk columns. The problem in https://asktug.com/t/topic/1010010 is that when adding TiFlash
 replica, the table `tgbk` does not contains gbk columns, and later, user use `alter table add column` to add a gbk column to `tgbk`, I think TiDB should throw error for this alter statement, and make sure that user can only add a gbk column after setting tiflash replica to 0

**Comment by windtalker** [comment]
Opened a TiDB issue: https://github.com/pingcap/tidb/issues/46041, close this one.

**Comment by shawn0915** [comment]
> Opened a TiDB issue: [pingcap/tidb#46041](https://github.com/pingcap/tidb/issues/46041), close this one.

@windtalker thanks for your hands up, then, let's see how to handle in tidb server.
