### ISSUE TITLE
Exception uncaught in LocalAdmissionController destructor

### ISSUE THREAD

**Issue by yibin87** [pingcap/tiflash#8459]
Found in daily regression with chaos. 
[BaseDaemon.cpp:361] [\"(from thread 1) Terminate called after throwing an instance of pingcap::Exception
Code: 2, e.displayText() = Exception: resource manager grpc call failed: AcquireTokenBuckets. write failed: failed to connect to all addresses, e.what() = Exception
Stack trace:
       0x7798c4d\\tterminate_handler() [tiflash+125406285]
                \\tlibs/libdaemon/src/BaseDaemon.cpp:628
  0x7ff025889a13\\tstd::__terminate(void (*)()) [libc++abi.so.1+236051]
  0x7ff0258899b8\\tstd::terminate() [libc++abi.so.1+235960]
       0x1ec9dfb\\t__clang_call_terminate [tiflash+32284155]
       0x1fbc961\\tDB::LocalAdmissionController::~LocalAdmissionController() [tiflash+33278305]
                \\tdbms/src/Flash/ResourceControl/LocalAdmissionController.h:445
       0x1fa226c\\tDB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) [tiflash+33170028]"]

**Comment by yibin87** [comment]
Labeled p2 and minor since it happened when server is about to shut down.

**Comment by guo-shaoge** [comment]
This problem can be caused by two reasons:
1. PD is down when tiflash try to send last LAC report to cleanup something in PD. 
2. tiflash got SIGTERM then grpc doesn't immediately, this canbe tricky. Because LAC have to send last rpc to do cleanup, but grpc cannot work at that time.

We need to make sure if this crash is caused by reason-1 or reason-2. If it's reason-1, we can just catch the exception. Otherwise we need to figure out others ways to send the last grpc to PD.

**Comment by guo-shaoge** [comment]
We can make sure this is caused by PD shutting down, so close
