### ISSUE TITLE
Optimize the performance of filtering data

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tiflash#9699]
## Enhancement
- [x] Optimize the performance of executing filtering https://github.com/pingcap/tiflash/pull/9670
- [ ] Only deserialize and copy the non-filtered rows https://github.com/pingcap/tiflash/pull/9678

**Comment by Lloyd-Pottiger** [comment]
When `deserializeBinaryBulk`, we will call `istr.readBig` to copy data from source to destination directly without copying to buffer. But if we only deserialize necessary rows, we can not call `istr.readBig` since the data size is small, so that data will be copied to the buffer first, and then copied to the destination. Therefore, there will be no improvement when only deserialize and copy the non-filtered rows.

https://github.com/pingcap/tiflash/blob/96ae6d220c50511a100c2439758ec6b515c91050/dbms/src/DataTypes/DataTypeNumberBase.cpp#L231-L245
